### ISSUE TITLE
ArduinoJson version 6 issue

### ISSUE THREAD

**Issue by e-m-m-a** [DoogeJ/esp8266-bitcoin-ssid-ticker#1]
Arduino: 1.8.9 (Linux), Board: "LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Disabled, 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

test:39:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
     DynamicJsonBuffer jsonBuffer(1100);
           ^
exit status 1
DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by NoxiousPluK** [comment]
Fixed in commit 4c9d432, thanks!
